language: python
python:
  - 2.6
  - 2.7
  - 3.3

# matrix:

install:
    - python bootstrap.py
    - 'if [[ x"$(python -V 2>&1)" == x"Python 3"* ]];then ./bin/buildout -c py3.cfg;fi'
    - 'if [[ x"$(python -V 2>&1)" == x"Python 2"* ]];then ./bin/buildout;fi'

script: bin/test
